# This GitHub action prettifies code.
name: CI-Prettier
on:
  pull_request:
    branches:
      - master
      - develop
jobs:
  prettier:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          # This is important to fetch the changes to the previous commit
          fetch-depth: 0
      - name: Prettify code
        uses: creyD/prettier_action@v4.2
        with:
          prettier_options: --write **/*.{ts,tsx,js,jsx,md}
          only_changed: True
          commit_message: "Prettify changed files"
          commit_options: "--author='poly-team-bot <thepolyteam.tech@gmail.com>'"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
