# Publish to NPM: only publish if version number is different.
name: CD - Build and Publish to NPM

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out Habits CLI code
        uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.17.6
      - run: npm install
      - name: Copy README.md
        run: cp docs/README.md .
      - run: npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
